language: node_js
node_js:
- '0.12'
branches:
  only:
  - blog

cache:
    directories:
        - node_modules

before_install:
- openssl aes-256-cbc -K $encrypted_86abc43bbd29_key -iv $encrypted_86abc43bbd29_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "researchlab"
- git config --global user.email inforoom@126.com 
- git clone -b master git@github.com:researchlab/researchlab.github.io.git .deploy_git
install:
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-deployer-git --save
script:
- hexo clean
- hexo g
- hexo d
